// Code generated by /tmp/gen_syscall_symbols_windows.go; DO NOT EDIT.
//go:build windows

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_windowscommon_Part05(t *testing.T) {
	_ = t
	var _ syscall.RawSockaddrInet6
	var _ syscall.RawSockaddrUnix
	_ = syscall.Read
	_ = syscall.ReadConsole
	_ = syscall.ReadDirectoryChanges
	_ = syscall.ReadFile
	_ = syscall.Readlink
	_ = syscall.Recvfrom
	_ = syscall.RegCloseKey
	_ = syscall.RegEnumKeyEx
	_ = syscall.RegOpenKeyEx
	_ = syscall.RegQueryInfoKey
	_ = syscall.RegQueryValueEx
	_ = syscall.RemoveDirectory
	_ = syscall.Rename
	_ = syscall.Rmdir
	var _ syscall.Rusage
	const _ = syscall.SHUT_RD
	const _ = syscall.SHUT_RDWR
	const _ = syscall.SHUT_WR
	var _ syscall.SID
	_ = (*syscall.SID).Copy
	_ = (*syscall.SID).Len
	_ = (*syscall.SID).LookupAccount
	_ = (*syscall.SID).String
	var _ syscall.SIDAndAttributes
	const _ = syscall.SIGABRT
	const _ = syscall.SIGALRM
	const _ = syscall.SIGBUS
	const _ = syscall.SIGFPE
	const _ = syscall.SIGHUP
	const _ = syscall.SIGILL
	const _ = syscall.SIGINT
	const _ = syscall.SIGKILL
	const _ = syscall.SIGPIPE
	const _ = syscall.SIGQUIT
	const _ = syscall.SIGSEGV
	const _ = syscall.SIGTERM
	const _ = syscall.SIGTRAP
	const _ = syscall.SIO_GET_EXTENSION_FUNCTION_POINTER
	const _ = syscall.SIO_GET_INTERFACE_LIST
	const _ = syscall.SIO_KEEPALIVE_VALS
	const _ = syscall.SIO_UDP_CONNRESET
	const _ = syscall.SOCK_DGRAM
	const _ = syscall.SOCK_RAW
	const _ = syscall.SOCK_SEQPACKET
	const _ = syscall.SOCK_STREAM
	const _ = syscall.SOL_SOCKET
	const _ = syscall.SOMAXCONN
	const _ = syscall.SO_BROADCAST
	const _ = syscall.SO_DONTROUTE
	const _ = syscall.SO_KEEPALIVE
	const _ = syscall.SO_LINGER
	const _ = syscall.SO_RCVBUF
	const _ = syscall.SO_REUSEADDR
	const _ = syscall.SO_SNDBUF
	const _ = syscall.SO_UPDATE_ACCEPT_CONTEXT
	const _ = syscall.SO_UPDATE_CONNECT_CONTEXT
	var _ syscall.SSLExtraCertChainPolicyPara
	const _ = syscall.STANDARD_RIGHTS_ALL
	const _ = syscall.STANDARD_RIGHTS_EXECUTE
	const _ = syscall.STANDARD_RIGHTS_READ
	const _ = syscall.STANDARD_RIGHTS_REQUIRED
	const _ = syscall.STANDARD_RIGHTS_WRITE
	const _ = syscall.STARTF_USESHOWWINDOW
	const _ = syscall.STARTF_USESTDHANDLES
	const _ = syscall.STD_ERROR_HANDLE
	const _ = syscall.STD_INPUT_HANDLE
	const _ = syscall.STD_OUTPUT_HANDLE
	const _ = syscall.SUBLANG_ENGLISH_US
	const _ = syscall.SW_FORCEMINIMIZE
	const _ = syscall.SW_HIDE
	const _ = syscall.SW_MAXIMIZE
	const _ = syscall.SW_MINIMIZE
	const _ = syscall.SW_NORMAL
	const _ = syscall.SW_RESTORE
	const _ = syscall.SW_SHOW
	const _ = syscall.SW_SHOWDEFAULT
	const _ = syscall.SW_SHOWMAXIMIZED
	const _ = syscall.SW_SHOWMINIMIZED
	const _ = syscall.SW_SHOWMINNOACTIVE
	const _ = syscall.SW_SHOWNA
	const _ = syscall.SW_SHOWNOACTIVATE
	const _ = syscall.SW_SHOWNORMAL
	const _ = syscall.SYMBOLIC_LINK_FLAG_DIRECTORY
	const _ = syscall.SYNCHRONIZE
	const _ = syscall.S_IFBLK
	const _ = syscall.S_IFCHR
	const _ = syscall.S_IFDIR
	const _ = syscall.S_IFIFO
	const _ = syscall.S_IFLNK
	const _ = syscall.S_IFMT
	const _ = syscall.S_IFREG
	const _ = syscall.S_IFSOCK
	const _ = syscall.S_IRUSR
	const _ = syscall.S_ISGID
	const _ = syscall.S_ISUID
	const _ = syscall.S_ISVTX
	const _ = syscall.S_IWRITE
	const _ = syscall.S_IWUSR
	const _ = syscall.S_IXUSR
	var _ syscall.SecurityAttributes
	_ = syscall.Seek
	_ = syscall.Sendto
	var _ syscall.Servent
	_ = syscall.SetCurrentDirectory
	_ = syscall.SetEndOfFile
	_ = syscall.SetEnvironmentVariable
	_ = syscall.SetFileAttributes
	_ = syscall.SetFileCompletionNotificationModes
	_ = syscall.SetFilePointer
	_ = syscall.SetFileTime
	_ = syscall.SetHandleInformation
	_ = syscall.SetNonblock
	_ = syscall.Setenv
	_ = syscall.Setsockopt
	_ = syscall.SetsockoptIPMreq
	_ = syscall.SetsockoptIPv6Mreq
	_ = syscall.SetsockoptInet4Addr
	_ = syscall.SetsockoptInt
	_ = syscall.SetsockoptLinger
	_ = syscall.SetsockoptTimeval
	_ = syscall.Shutdown
	const _ = syscall.SidTypeAlias
	const _ = syscall.SidTypeComputer
	const _ = syscall.SidTypeDeletedAccount
	const _ = syscall.SidTypeDomain
	const _ = syscall.SidTypeGroup
	const _ = syscall.SidTypeInvalid
	const _ = syscall.SidTypeLabel
	const _ = syscall.SidTypeUnknown
	const _ = syscall.SidTypeUser
	const _ = syscall.SidTypeWellKnownGroup
	var _ syscall.Signal
	_ = (*syscall.Signal).Signal
	_ = (*syscall.Signal).String
	var _ syscall.Sockaddr
	var _ syscall.SockaddrGen
	var _ syscall.SockaddrInet4
	var _ syscall.SockaddrInet6
	var _ syscall.SockaddrUnix
	_ = syscall.Socket
	_ = syscall.SocketDisableIPv6
	_ = syscall.StartProcess
	var _ syscall.StartupInfo
	_ = syscall.Stderr
	_ = syscall.Stdin
	_ = syscall.Stdout
	_ = syscall.StringBytePtr
	_ = syscall.StringByteSlice
	_ = syscall.StringToSid
	_ = syscall.StringToUTF16
	_ = syscall.StringToUTF16Ptr
	_ = syscall.Symlink
	var _ syscall.SysProcAttr
	_ = syscall.Syscall
	_ = syscall.Syscall12
	_ = syscall.Syscall15
	_ = syscall.Syscall18
	_ = syscall.Syscall6
	_ = syscall.Syscall9
	_ = syscall.SyscallN
	var _ syscall.Systemtime
	var _ syscall.TCPKeepalive
	const _ = syscall.TCP_NODELAY
	const _ = syscall.TF_DISCONNECT
	const _ = syscall.TF_REUSE_SOCKET
	const _ = syscall.TF_USE_DEFAULT_WORKER
	const _ = syscall.TF_USE_KERNEL_APC
	const _ = syscall.TF_USE_SYSTEM_THREAD
	const _ = syscall.TF_WRITE_BEHIND
	const _ = syscall.TH32CS_INHERIT
	const _ = syscall.TH32CS_SNAPALL
	const _ = syscall.TH32CS_SNAPHEAPLIST
	const _ = syscall.TH32CS_SNAPMODULE
	const _ = syscall.TH32CS_SNAPMODULE32
	const _ = syscall.TH32CS_SNAPPROCESS
	const _ = syscall.TH32CS_SNAPTHREAD
	const _ = syscall.TIME_ZONE_ID_DAYLIGHT
	const _ = syscall.TIME_ZONE_ID_STANDARD
}
