// Code generated by /tmp/gen_syscall_symbols_windows.go; DO NOT EDIT.
//go:build windows

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_windowscommon_Part04(t *testing.T) {
	_ = t
	const _ = syscall.IP_DROP_MEMBERSHIP
	const _ = syscall.IP_MULTICAST_IF
	const _ = syscall.IP_MULTICAST_LOOP
	const _ = syscall.IP_MULTICAST_TTL
	const _ = syscall.IP_TOS
	const _ = syscall.IP_TTL
	var _ syscall.IPv6Mreq
	const _ = syscall.ImplementsGetwd
	var _ syscall.InterfaceInfo
	const _ = syscall.InvalidHandle
	var _ syscall.IpAdapterInfo
	var _ syscall.IpAddrString
	var _ syscall.IpAddressString
	var _ syscall.IpMaskString
	const _ = syscall.KEY_ALL_ACCESS
	const _ = syscall.KEY_CREATE_LINK
	const _ = syscall.KEY_CREATE_SUB_KEY
	const _ = syscall.KEY_ENUMERATE_SUB_KEYS
	const _ = syscall.KEY_EXECUTE
	const _ = syscall.KEY_NOTIFY
	const _ = syscall.KEY_QUERY_VALUE
	const _ = syscall.KEY_READ
	const _ = syscall.KEY_SET_VALUE
	const _ = syscall.KEY_WOW64_32KEY
	const _ = syscall.KEY_WOW64_64KEY
	const _ = syscall.KEY_WRITE
	const _ = syscall.LANG_ENGLISH
	const _ = syscall.LAYERED_PROTOCOL
	var _ syscall.LazyDLL
	_ = (*syscall.LazyDLL).Handle
	_ = (*syscall.LazyDLL).Load
	_ = (*syscall.LazyDLL).NewProc
	var _ syscall.LazyProc
	_ = (*syscall.LazyProc).Addr
	_ = (*syscall.LazyProc).Call
	_ = (*syscall.LazyProc).Find
	_ = syscall.Lchown
	var _ syscall.Linger
	_ = syscall.Link
	_ = syscall.Listen
	_ = syscall.LoadCancelIoEx
	_ = syscall.LoadConnectEx
	_ = syscall.LoadCreateSymbolicLink
	_ = syscall.LoadDLL
	_ = syscall.LoadGetAddrInfo
	_ = syscall.LoadLibrary
	_ = syscall.LoadSetFileCompletionNotificationModes
	_ = syscall.LocalFree
	_ = syscall.LookupAccountName
	_ = syscall.LookupAccountSid
	_ = syscall.LookupSID
	const _ = syscall.MAXIMUM_REPARSE_DATA_BUFFER_SIZE
	const _ = syscall.MAXLEN_IFDESCR
	const _ = syscall.MAXLEN_PHYSADDR
	const _ = syscall.MAX_ADAPTER_ADDRESS_LENGTH
	const _ = syscall.MAX_ADAPTER_DESCRIPTION_LENGTH
	const _ = syscall.MAX_ADAPTER_NAME_LENGTH
	const _ = syscall.MAX_COMPUTERNAME_LENGTH
	const _ = syscall.MAX_INTERFACE_NAME_LEN
	const _ = syscall.MAX_LONG_PATH
	const _ = syscall.MAX_PATH
	const _ = syscall.MAX_PROTOCOL_CHAIN
	_ = syscall.MapViewOfFile
	const _ = syscall.MaxTokenInfoClass
	var _ syscall.MibIfRow
	_ = syscall.Mkdir
	_ = syscall.MoveFile
	_ = syscall.MustLoadDLL
	const _ = syscall.NameCanonical
	const _ = syscall.NameCanonicalEx
	const _ = syscall.NameDisplay
	const _ = syscall.NameDnsDomain
	const _ = syscall.NameFullyQualifiedDN
	const _ = syscall.NameSamCompatible
	const _ = syscall.NameServicePrincipal
	const _ = syscall.NameUniqueId
	const _ = syscall.NameUnknown
	const _ = syscall.NameUserPrincipal
	_ = syscall.NetApiBufferFree
	_ = syscall.NetGetJoinInformation
	const _ = syscall.NetSetupDomainName
	const _ = syscall.NetSetupUnjoined
	const _ = syscall.NetSetupUnknownStatus
	const _ = syscall.NetSetupWorkgroupName
	_ = syscall.NetUserGetInfo
	_ = syscall.NewCallback
	_ = syscall.NewCallbackCDecl
	_ = syscall.NewLazyDLL
	_ = syscall.NsecToFiletime
	_ = syscall.NsecToTimespec
	_ = syscall.NsecToTimeval
	_ = syscall.Ntohs
	_ = syscall.OID_PKIX_KP_SERVER_AUTH
	_ = syscall.OID_SERVER_GATED_CRYPTO
	_ = syscall.OID_SGC_NETSCAPE
	const _ = syscall.OPEN_ALWAYS
	const _ = syscall.OPEN_EXISTING
	const _ = syscall.O_APPEND
	const _ = syscall.O_ASYNC
	const _ = syscall.O_CLOEXEC
	const _ = syscall.O_CREAT
	const _ = syscall.O_EXCL
	const _ = syscall.O_NOCTTY
	const _ = syscall.O_NONBLOCK
	const _ = syscall.O_RDONLY
	const _ = syscall.O_RDWR
	const _ = syscall.O_SYNC
	const _ = syscall.O_TRUNC
	const _ = syscall.O_WRONLY
	_ = syscall.Open
	_ = syscall.OpenCurrentProcessToken
	_ = syscall.OpenProcess
	_ = syscall.OpenProcessToken
	var _ syscall.Overlapped
	const _ = syscall.PAGE_EXECUTE_READ
	const _ = syscall.PAGE_EXECUTE_READWRITE
	const _ = syscall.PAGE_EXECUTE_WRITECOPY
	const _ = syscall.PAGE_READONLY
	const _ = syscall.PAGE_READWRITE
	const _ = syscall.PAGE_WRITECOPY
	const _ = syscall.PFL_HIDDEN
	const _ = syscall.PFL_MATCHES_PROTOCOL_ZERO
	const _ = syscall.PFL_MULTIPLE_PROTO_ENTRIES
	const _ = syscall.PFL_NETWORKDIRECT_PROVIDER
	const _ = syscall.PFL_RECOMMENDED_PROTO_ENTRY
	const _ = syscall.PKCS_7_ASN_ENCODING
	const _ = syscall.PROCESS_QUERY_INFORMATION
	const _ = syscall.PROCESS_TERMINATE
	const _ = syscall.PROV_DH_SCHANNEL
	const _ = syscall.PROV_DSS
	const _ = syscall.PROV_DSS_DH
	const _ = syscall.PROV_EC_ECDSA_FULL
	const _ = syscall.PROV_EC_ECDSA_SIG
	const _ = syscall.PROV_EC_ECNRA_FULL
	const _ = syscall.PROV_EC_ECNRA_SIG
	const _ = syscall.PROV_FORTEZZA
	const _ = syscall.PROV_INTEL_SEC
	const _ = syscall.PROV_MS_EXCHANGE
	const _ = syscall.PROV_REPLACE_OWF
	const _ = syscall.PROV_RNG
	const _ = syscall.PROV_RSA_AES
	const _ = syscall.PROV_RSA_FULL
	const _ = syscall.PROV_RSA_SCHANNEL
	const _ = syscall.PROV_RSA_SIG
	const _ = syscall.PROV_SPYRUS_LYNKS
	const _ = syscall.PROV_SSL
	_ = syscall.Pipe
	var _ syscall.Pointer
	_ = syscall.PostQueuedCompletionStatus
	var _ syscall.Proc
	_ = (*syscall.Proc).Addr
	_ = (*syscall.Proc).Call
	var _ syscall.ProcAttr
	_ = syscall.Process32First
	_ = syscall.Process32Next
	var _ syscall.ProcessEntry32
	var _ syscall.ProcessInformation
	var _ syscall.Protoent
	const _ = syscall.REG_BINARY
	const _ = syscall.REG_DWORD
	const _ = syscall.REG_DWORD_BIG_ENDIAN
	const _ = syscall.REG_DWORD_LITTLE_ENDIAN
	const _ = syscall.REG_EXPAND_SZ
	const _ = syscall.REG_FULL_RESOURCE_DESCRIPTOR
	const _ = syscall.REG_LINK
	const _ = syscall.REG_MULTI_SZ
	const _ = syscall.REG_NONE
	const _ = syscall.REG_QWORD
	const _ = syscall.REG_QWORD_LITTLE_ENDIAN
	const _ = syscall.REG_RESOURCE_LIST
	const _ = syscall.REG_RESOURCE_REQUIREMENTS_LIST
	const _ = syscall.REG_SZ
	var _ syscall.RawConn
	_ = syscall.RawConn.Control
	_ = syscall.RawConn.Read
	_ = syscall.RawConn.Write
	var _ syscall.RawSockaddr
	var _ syscall.RawSockaddrAny
	_ = (*syscall.RawSockaddrAny).Sockaddr
	var _ syscall.RawSockaddrInet4
}
