// Code generated by /tmp/gen_syscall_symbols_windows.go; DO NOT EDIT.
//go:build windows

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_windowscommon_Part06(t *testing.T) {
	_ = t
	const _ = syscall.TIME_ZONE_ID_UNKNOWN
	const _ = syscall.TOKEN_ADJUST_DEFAULT
	const _ = syscall.TOKEN_ADJUST_GROUPS
	const _ = syscall.TOKEN_ADJUST_PRIVILEGES
	const _ = syscall.TOKEN_ADJUST_SESSIONID
	const _ = syscall.TOKEN_ALL_ACCESS
	const _ = syscall.TOKEN_ASSIGN_PRIMARY
	const _ = syscall.TOKEN_DUPLICATE
	const _ = syscall.TOKEN_EXECUTE
	const _ = syscall.TOKEN_IMPERSONATE
	const _ = syscall.TOKEN_QUERY
	const _ = syscall.TOKEN_QUERY_SOURCE
	const _ = syscall.TOKEN_READ
	const _ = syscall.TOKEN_WRITE
	const _ = syscall.TRUNCATE_EXISTING
	_ = syscall.TerminateProcess
	var _ syscall.Timespec
	_ = (*syscall.Timespec).Nano
	_ = (*syscall.Timespec).Unix
	_ = syscall.TimespecToNsec
	var _ syscall.Timeval
	_ = (*syscall.Timeval).Nano
	_ = (*syscall.Timeval).Nanoseconds
	_ = (*syscall.Timeval).Unix
	var _ syscall.Timezoneinformation
	var _ syscall.Token
	_ = (*syscall.Token).Close
	_ = (*syscall.Token).GetTokenPrimaryGroup
	_ = (*syscall.Token).GetTokenUser
	_ = (*syscall.Token).GetUserProfileDirectory
	const _ = syscall.TokenAccessInformation
	const _ = syscall.TokenAuditPolicy
	const _ = syscall.TokenDefaultDacl
	const _ = syscall.TokenElevation
	const _ = syscall.TokenElevationType
	const _ = syscall.TokenGroups
	const _ = syscall.TokenGroupsAndPrivileges
	const _ = syscall.TokenHasRestrictions
	const _ = syscall.TokenImpersonationLevel
	const _ = syscall.TokenIntegrityLevel
	const _ = syscall.TokenLinkedToken
	const _ = syscall.TokenLogonSid
	const _ = syscall.TokenMandatoryPolicy
	const _ = syscall.TokenOrigin
	const _ = syscall.TokenOwner
	const _ = syscall.TokenPrimaryGroup
	const _ = syscall.TokenPrivileges
	const _ = syscall.TokenRestrictedSids
	const _ = syscall.TokenSandBoxInert
	const _ = syscall.TokenSessionId
	const _ = syscall.TokenSessionReference
	const _ = syscall.TokenSource
	const _ = syscall.TokenStatistics
	const _ = syscall.TokenType
	const _ = syscall.TokenUIAccess
	const _ = syscall.TokenUser
	const _ = syscall.TokenVirtualizationAllowed
	const _ = syscall.TokenVirtualizationEnabled
	var _ syscall.Tokenprimarygroup
	var _ syscall.Tokenuser
	_ = syscall.TranslateAccountName
	_ = syscall.TranslateName
	_ = syscall.TransmitFile
	var _ syscall.TransmitFileBuffers
	const _ = syscall.UNIX_PATH_MAX
	const _ = syscall.USAGE_MATCH_TYPE_AND
	const _ = syscall.USAGE_MATCH_TYPE_OR
	_ = syscall.UTF16FromString
	_ = syscall.UTF16PtrFromString
	_ = syscall.UTF16ToString
	_ = syscall.Unlink
	_ = syscall.UnmapViewOfFile
	_ = syscall.Unsetenv
	var _ syscall.UserInfo10
	_ = syscall.Utimes
	_ = syscall.UtimesNano
	_ = syscall.VirtualLock
	_ = syscall.VirtualUnlock
	const _ = syscall.WAIT_ABANDONED
	const _ = syscall.WAIT_FAILED
	const _ = syscall.WAIT_OBJECT_0
	const _ = syscall.WAIT_TIMEOUT
	var _ syscall.WSABuf
	_ = syscall.WSACleanup
	const _ = syscall.WSADESCRIPTION_LEN
	var _ syscall.WSAData
	const _ = syscall.WSAEACCES
	const _ = syscall.WSAECONNABORTED
	const _ = syscall.WSAECONNRESET
	const _ = syscall.WSAENOPROTOOPT
	_ = syscall.WSAEnumProtocols
	_ = syscall.WSAID_CONNECTEX
	_ = syscall.WSAIoctl
	const _ = syscall.WSAPROTOCOL_LEN
	var _ syscall.WSAProtocolChain
	var _ syscall.WSAProtocolInfo
	_ = syscall.WSARecv
	_ = syscall.WSARecvFrom
	const _ = syscall.WSASYS_STATUS_LEN
	_ = syscall.WSASend
	_ = syscall.WSASendTo
	_ = syscall.WSASendto
	_ = syscall.WSAStartup
	_ = syscall.WaitForSingleObject
	var _ syscall.WaitStatus
	_ = (*syscall.WaitStatus).Continued
	_ = (*syscall.WaitStatus).CoreDump
	_ = (*syscall.WaitStatus).ExitStatus
	_ = (*syscall.WaitStatus).Exited
	_ = (*syscall.WaitStatus).Signal
	_ = (*syscall.WaitStatus).Signaled
	_ = (*syscall.WaitStatus).StopSignal
	_ = (*syscall.WaitStatus).Stopped
	_ = (*syscall.WaitStatus).TrapCause
	var _ syscall.Win32FileAttributeData
	var _ syscall.Win32finddata
	_ = syscall.Write
	_ = syscall.WriteConsole
	_ = syscall.WriteFile
	const _ = syscall.X509_ASN_ENCODING
	const _ = syscall.XP1_CONNECTIONLESS
	const _ = syscall.XP1_CONNECT_DATA
	const _ = syscall.XP1_DISCONNECT_DATA
	const _ = syscall.XP1_EXPEDITED_DATA
	const _ = syscall.XP1_GRACEFUL_CLOSE
	const _ = syscall.XP1_GUARANTEED_DELIVERY
	const _ = syscall.XP1_GUARANTEED_ORDER
	const _ = syscall.XP1_IFS_HANDLES
	const _ = syscall.XP1_MESSAGE_ORIENTED
	const _ = syscall.XP1_MULTIPOINT_CONTROL_PLANE
	const _ = syscall.XP1_MULTIPOINT_DATA_PLANE
	const _ = syscall.XP1_PARTIAL_MESSAGE
	const _ = syscall.XP1_PSEUDO_STREAM
	const _ = syscall.XP1_QOS_SUPPORTED
	const _ = syscall.XP1_SAN_SUPPORT_SDP
	const _ = syscall.XP1_SUPPORT_BROADCAST
	const _ = syscall.XP1_SUPPORT_MULTIPOINT
	const _ = syscall.XP1_UNI_RECV
	const _ = syscall.XP1_UNI_SEND
}
