// Code generated by /tmp/gen_syscall_symbols_windows.go; DO NOT EDIT.
//go:build windows

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_windowscommon_Part03(t *testing.T) {
	_ = t
	const _ = syscall.EUNATCH
	const _ = syscall.EUSERS
	const _ = syscall.EWINDOWS
	const _ = syscall.EWOULDBLOCK
	const _ = syscall.EXDEV
	const _ = syscall.EXFULL
	_ = syscall.Environ
	var _ syscall.Errno
	_ = (*syscall.Errno).Error
	_ = (*syscall.Errno).Is
	_ = (*syscall.Errno).Temporary
	_ = (*syscall.Errno).Timeout
	_ = syscall.EscapeArg
	_ = syscall.Exec
	_ = syscall.Exit
	_ = syscall.ExitProcess
	const _ = syscall.FILE_ACTION_ADDED
	const _ = syscall.FILE_ACTION_MODIFIED
	const _ = syscall.FILE_ACTION_REMOVED
	const _ = syscall.FILE_ACTION_RENAMED_NEW_NAME
	const _ = syscall.FILE_ACTION_RENAMED_OLD_NAME
	const _ = syscall.FILE_APPEND_DATA
	const _ = syscall.FILE_ATTRIBUTE_ARCHIVE
	const _ = syscall.FILE_ATTRIBUTE_DIRECTORY
	const _ = syscall.FILE_ATTRIBUTE_HIDDEN
	const _ = syscall.FILE_ATTRIBUTE_NORMAL
	const _ = syscall.FILE_ATTRIBUTE_READONLY
	const _ = syscall.FILE_ATTRIBUTE_REPARSE_POINT
	const _ = syscall.FILE_ATTRIBUTE_SYSTEM
	const _ = syscall.FILE_BEGIN
	const _ = syscall.FILE_CURRENT
	const _ = syscall.FILE_END
	const _ = syscall.FILE_FLAG_BACKUP_SEMANTICS
	const _ = syscall.FILE_FLAG_OPEN_REPARSE_POINT
	const _ = syscall.FILE_FLAG_OVERLAPPED
	const _ = syscall.FILE_LIST_DIRECTORY
	const _ = syscall.FILE_MAP_COPY
	const _ = syscall.FILE_MAP_EXECUTE
	const _ = syscall.FILE_MAP_READ
	const _ = syscall.FILE_MAP_WRITE
	const _ = syscall.FILE_NOTIFY_CHANGE_ATTRIBUTES
	const _ = syscall.FILE_NOTIFY_CHANGE_CREATION
	const _ = syscall.FILE_NOTIFY_CHANGE_DIR_NAME
	const _ = syscall.FILE_NOTIFY_CHANGE_FILE_NAME
	const _ = syscall.FILE_NOTIFY_CHANGE_LAST_ACCESS
	const _ = syscall.FILE_NOTIFY_CHANGE_LAST_WRITE
	const _ = syscall.FILE_NOTIFY_CHANGE_SIZE
	const _ = syscall.FILE_SHARE_DELETE
	const _ = syscall.FILE_SHARE_READ
	const _ = syscall.FILE_SHARE_WRITE
	const _ = syscall.FILE_SKIP_COMPLETION_PORT_ON_SUCCESS
	const _ = syscall.FILE_SKIP_SET_EVENT_ON_HANDLE
	const _ = syscall.FILE_TYPE_CHAR
	const _ = syscall.FILE_TYPE_DISK
	const _ = syscall.FILE_TYPE_PIPE
	const _ = syscall.FILE_TYPE_REMOTE
	const _ = syscall.FILE_TYPE_UNKNOWN
	const _ = syscall.FILE_WRITE_ATTRIBUTES
	const _ = syscall.FORMAT_MESSAGE_ALLOCATE_BUFFER
	const _ = syscall.FORMAT_MESSAGE_ARGUMENT_ARRAY
	const _ = syscall.FORMAT_MESSAGE_FROM_HMODULE
	const _ = syscall.FORMAT_MESSAGE_FROM_STRING
	const _ = syscall.FORMAT_MESSAGE_FROM_SYSTEM
	const _ = syscall.FORMAT_MESSAGE_IGNORE_INSERTS
	const _ = syscall.FORMAT_MESSAGE_MAX_WIDTH_MASK
	const _ = syscall.FSCTL_GET_REPARSE_POINT
	_ = syscall.Fchdir
	_ = syscall.Fchmod
	_ = syscall.Fchown
	var _ syscall.FileNotifyInformation
	var _ syscall.Filetime
	_ = (*syscall.Filetime).Nanoseconds
	_ = syscall.FindClose
	_ = syscall.FindFirstFile
	_ = syscall.FindNextFile
	_ = syscall.FlushFileBuffers
	_ = syscall.FlushViewOfFile
	_ = syscall.ForkLock
	_ = syscall.FormatMessage
	_ = syscall.FreeAddrInfoW
	_ = syscall.FreeEnvironmentStrings
	_ = syscall.FreeLibrary
	_ = syscall.Fsync
	_ = syscall.Ftruncate
	_ = syscall.FullPath
	const _ = syscall.GENERIC_ALL
	const _ = syscall.GENERIC_EXECUTE
	const _ = syscall.GENERIC_READ
	const _ = syscall.GENERIC_WRITE
	var _ syscall.GUID
	_ = syscall.GetAcceptExSockaddrs
	_ = syscall.GetAdaptersInfo
	_ = syscall.GetAddrInfoW
	_ = syscall.GetCommandLine
	_ = syscall.GetComputerName
	_ = syscall.GetConsoleMode
	_ = syscall.GetCurrentDirectory
	_ = syscall.GetCurrentProcess
	_ = syscall.GetEnvironmentStrings
	_ = syscall.GetEnvironmentVariable
	_ = syscall.GetExitCodeProcess
	_ = syscall.GetFileAttributes
	_ = syscall.GetFileAttributesEx
	const _ = syscall.GetFileExInfoStandard
	const _ = syscall.GetFileExMaxInfoLevel
	_ = syscall.GetFileInformationByHandle
	_ = syscall.GetFileType
	_ = syscall.GetFullPathName
	_ = syscall.GetHostByName
	_ = syscall.GetIfEntry
	_ = syscall.GetLastError
	_ = syscall.GetLengthSid
	_ = syscall.GetLongPathName
	_ = syscall.GetProcAddress
	_ = syscall.GetProcessTimes
	_ = syscall.GetProtoByName
	_ = syscall.GetQueuedCompletionStatus
	_ = syscall.GetServByName
	_ = syscall.GetShortPathName
	_ = syscall.GetStartupInfo
	_ = syscall.GetStdHandle
	_ = syscall.GetSystemTimeAsFileTime
	_ = syscall.GetTempPath
	_ = syscall.GetTimeZoneInformation
	_ = syscall.GetTokenInformation
	_ = syscall.GetUserNameEx
	_ = syscall.GetUserProfileDirectory
	_ = syscall.GetVersion
	_ = syscall.Getegid
	_ = syscall.Getenv
	_ = syscall.Geteuid
	_ = syscall.Getgid
	_ = syscall.Getgroups
	_ = syscall.Getpagesize
	_ = syscall.Getpeername
	_ = syscall.Getpid
	_ = syscall.Getppid
	_ = syscall.Getsockname
	_ = syscall.Getsockopt
	_ = syscall.GetsockoptInt
	_ = syscall.Gettimeofday
	_ = syscall.Getuid
	_ = syscall.Getwd
	const _ = syscall.HANDLE_FLAG_INHERIT
	const _ = syscall.HKEY_CLASSES_ROOT
	const _ = syscall.HKEY_CURRENT_CONFIG
	const _ = syscall.HKEY_CURRENT_USER
	const _ = syscall.HKEY_DYN_DATA
	const _ = syscall.HKEY_LOCAL_MACHINE
	const _ = syscall.HKEY_PERFORMANCE_DATA
	const _ = syscall.HKEY_USERS
	var _ syscall.Handle
	var _ syscall.Hostent
	const _ = syscall.IFF_BROADCAST
	const _ = syscall.IFF_LOOPBACK
	const _ = syscall.IFF_MULTICAST
	const _ = syscall.IFF_POINTTOPOINT
	const _ = syscall.IFF_UP
	const _ = syscall.IGNORE
	const _ = syscall.INFINITE
	const _ = syscall.INVALID_FILE_ATTRIBUTES
	const _ = syscall.IOC_IN
	const _ = syscall.IOC_INOUT
	const _ = syscall.IOC_OUT
	const _ = syscall.IOC_VENDOR
	const _ = syscall.IOC_WS2
	const _ = syscall.IO_REPARSE_TAG_SYMLINK
	var _ syscall.IPMreq
	const _ = syscall.IPPROTO_IP
	const _ = syscall.IPPROTO_IPV6
	const _ = syscall.IPPROTO_TCP
	const _ = syscall.IPPROTO_UDP
	const _ = syscall.IPV6_JOIN_GROUP
	const _ = syscall.IPV6_LEAVE_GROUP
	const _ = syscall.IPV6_MULTICAST_HOPS
	const _ = syscall.IPV6_MULTICAST_IF
	const _ = syscall.IPV6_MULTICAST_LOOP
	const _ = syscall.IPV6_UNICAST_HOPS
	const _ = syscall.IPV6_V6ONLY
	const _ = syscall.IP_ADD_MEMBERSHIP
}
