// Code generated by /tmp/gen_syscall_symbols_windows.go; DO NOT EDIT.
//go:build windows

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_windowscommon_Part01(t *testing.T) {
	_ = t
	const _ = syscall.AF_INET
	const _ = syscall.AF_INET6
	const _ = syscall.AF_NETBIOS
	const _ = syscall.AF_UNIX
	const _ = syscall.AF_UNSPEC
	const _ = syscall.AI_CANONNAME
	const _ = syscall.AI_NUMERICHOST
	const _ = syscall.AI_PASSIVE
	const _ = syscall.APPLICATION_ERROR
	const _ = syscall.AUTHTYPE_CLIENT
	const _ = syscall.AUTHTYPE_SERVER
	_ = syscall.Accept
	_ = syscall.AcceptEx
	var _ syscall.AddrinfoW
	const _ = syscall.BASE_PROTOCOL
	_ = syscall.Bind
	var _ syscall.ByHandleFileInformation
	_ = syscall.BytePtrFromString
	_ = syscall.ByteSliceFromString
	const _ = syscall.CERT_CHAIN_POLICY_AUTHENTICODE
	const _ = syscall.CERT_CHAIN_POLICY_AUTHENTICODE_TS
	const _ = syscall.CERT_CHAIN_POLICY_BASE
	const _ = syscall.CERT_CHAIN_POLICY_BASIC_CONSTRAINTS
	const _ = syscall.CERT_CHAIN_POLICY_EV
	const _ = syscall.CERT_CHAIN_POLICY_MICROSOFT_ROOT
	const _ = syscall.CERT_CHAIN_POLICY_NT_AUTH
	const _ = syscall.CERT_CHAIN_POLICY_SSL
	const _ = syscall.CERT_E_CN_NO_MATCH
	const _ = syscall.CERT_E_EXPIRED
	const _ = syscall.CERT_E_PURPOSE
	const _ = syscall.CERT_E_ROLE
	const _ = syscall.CERT_E_UNTRUSTEDROOT
	const _ = syscall.CERT_STORE_ADD_ALWAYS
	const _ = syscall.CERT_STORE_DEFER_CLOSE_UNTIL_LAST_FREE_FLAG
	const _ = syscall.CERT_STORE_PROV_MEMORY
	const _ = syscall.CERT_TRUST_HAS_EXCLUDED_NAME_CONSTRAINT
	const _ = syscall.CERT_TRUST_HAS_NOT_DEFINED_NAME_CONSTRAINT
	const _ = syscall.CERT_TRUST_HAS_NOT_PERMITTED_NAME_CONSTRAINT
	const _ = syscall.CERT_TRUST_HAS_NOT_SUPPORTED_CRITICAL_EXT
	const _ = syscall.CERT_TRUST_HAS_NOT_SUPPORTED_NAME_CONSTRAINT
	const _ = syscall.CERT_TRUST_INVALID_BASIC_CONSTRAINTS
	const _ = syscall.CERT_TRUST_INVALID_EXTENSION
	const _ = syscall.CERT_TRUST_INVALID_NAME_CONSTRAINTS
	const _ = syscall.CERT_TRUST_INVALID_POLICY_CONSTRAINTS
	const _ = syscall.CERT_TRUST_IS_CYCLIC
	const _ = syscall.CERT_TRUST_IS_EXPLICIT_DISTRUST
	const _ = syscall.CERT_TRUST_IS_NOT_SIGNATURE_VALID
	const _ = syscall.CERT_TRUST_IS_NOT_TIME_VALID
	const _ = syscall.CERT_TRUST_IS_NOT_VALID_FOR_USAGE
	const _ = syscall.CERT_TRUST_IS_OFFLINE_REVOCATION
	const _ = syscall.CERT_TRUST_IS_REVOKED
	const _ = syscall.CERT_TRUST_IS_UNTRUSTED_ROOT
	const _ = syscall.CERT_TRUST_NO_ERROR
	const _ = syscall.CERT_TRUST_NO_ISSUANCE_CHAIN_POLICY
	const _ = syscall.CERT_TRUST_REVOCATION_STATUS_UNKNOWN
	const _ = syscall.CREATE_ALWAYS
	const _ = syscall.CREATE_NEW
	const _ = syscall.CREATE_NEW_PROCESS_GROUP
	const _ = syscall.CREATE_UNICODE_ENVIRONMENT
	const _ = syscall.CRYPT_DEFAULT_CONTAINER_OPTIONAL
	const _ = syscall.CRYPT_DELETEKEYSET
	const _ = syscall.CRYPT_MACHINE_KEYSET
	const _ = syscall.CRYPT_NEWKEYSET
	const _ = syscall.CRYPT_SILENT
	const _ = syscall.CRYPT_VERIFYCONTEXT
	const _ = syscall.CTRL_BREAK_EVENT
	const _ = syscall.CTRL_CLOSE_EVENT
	const _ = syscall.CTRL_C_EVENT
	const _ = syscall.CTRL_LOGOFF_EVENT
	const _ = syscall.CTRL_SHUTDOWN_EVENT
	_ = syscall.CancelIo
	_ = syscall.CancelIoEx
	_ = syscall.CertAddCertificateContextToStore
	var _ syscall.CertChainContext
	var _ syscall.CertChainElement
	var _ syscall.CertChainPara
	var _ syscall.CertChainPolicyPara
	var _ syscall.CertChainPolicyStatus
	_ = syscall.CertCloseStore
	var _ syscall.CertContext
	_ = syscall.CertCreateCertificateContext
	var _ syscall.CertEnhKeyUsage
	_ = syscall.CertEnumCertificatesInStore
	_ = syscall.CertFreeCertificateChain
	_ = syscall.CertFreeCertificateContext
	_ = syscall.CertGetCertificateChain
	var _ syscall.CertInfo
	_ = syscall.CertOpenStore
	_ = syscall.CertOpenSystemStore
	var _ syscall.CertRevocationCrlInfo
	var _ syscall.CertRevocationInfo
	var _ syscall.CertSimpleChain
	var _ syscall.CertTrustListInfo
	var _ syscall.CertTrustStatus
	var _ syscall.CertUsageMatch
	_ = syscall.CertVerifyCertificateChainPolicy
	_ = syscall.Chdir
	_ = syscall.Chmod
	_ = syscall.Chown
	_ = syscall.Clearenv
	_ = syscall.Close
	_ = syscall.CloseHandle
	_ = syscall.CloseOnExec
	_ = syscall.Closesocket
	_ = syscall.CommandLineToArgv
	_ = syscall.ComputerName
	var _ syscall.Conn
	_ = syscall.Conn.SyscallConn
	_ = syscall.Connect
	_ = syscall.ConnectEx
	_ = syscall.ConvertSidToStringSid
	_ = syscall.ConvertStringSidToSid
	_ = syscall.CopySid
	_ = syscall.CreateDirectory
	_ = syscall.CreateFile
	_ = syscall.CreateFileMapping
	_ = syscall.CreateHardLink
	_ = syscall.CreateIoCompletionPort
	_ = syscall.CreatePipe
	_ = syscall.CreateProcess
	_ = syscall.CreateProcessAsUser
	_ = syscall.CreateSymbolicLink
	_ = syscall.CreateToolhelp32Snapshot
	_ = syscall.CryptAcquireContext
	_ = syscall.CryptGenRandom
	_ = syscall.CryptReleaseContext
	var _ syscall.DLL
	_ = (*syscall.DLL).FindProc
	_ = (*syscall.DLL).MustFindProc
	_ = (*syscall.DLL).Release
	var _ syscall.DLLError
	_ = (*syscall.DLLError).Error
	_ = (*syscall.DLLError).Unwrap
	var _ syscall.DNSMXData
	var _ syscall.DNSPTRData
	var _ syscall.DNSRecord
	var _ syscall.DNSSRVData
	var _ syscall.DNSTXTData
	const _ = syscall.DNS_INFO_NO_RECORDS
	const _ = syscall.DNS_TYPE_A
	const _ = syscall.DNS_TYPE_A6
	const _ = syscall.DNS_TYPE_AAAA
	const _ = syscall.DNS_TYPE_ADDRS
	const _ = syscall.DNS_TYPE_AFSDB
	const _ = syscall.DNS_TYPE_ALL
	const _ = syscall.DNS_TYPE_ANY
	const _ = syscall.DNS_TYPE_ATMA
	const _ = syscall.DNS_TYPE_AXFR
	const _ = syscall.DNS_TYPE_CERT
	const _ = syscall.DNS_TYPE_CNAME
	const _ = syscall.DNS_TYPE_DHCID
	const _ = syscall.DNS_TYPE_DNAME
	const _ = syscall.DNS_TYPE_DNSKEY
	const _ = syscall.DNS_TYPE_DS
	const _ = syscall.DNS_TYPE_EID
	const _ = syscall.DNS_TYPE_GID
	const _ = syscall.DNS_TYPE_GPOS
	const _ = syscall.DNS_TYPE_HINFO
	const _ = syscall.DNS_TYPE_ISDN
	const _ = syscall.DNS_TYPE_IXFR
	const _ = syscall.DNS_TYPE_KEY
	const _ = syscall.DNS_TYPE_KX
	const _ = syscall.DNS_TYPE_LOC
	const _ = syscall.DNS_TYPE_MAILA
	const _ = syscall.DNS_TYPE_MAILB
	const _ = syscall.DNS_TYPE_MB
	const _ = syscall.DNS_TYPE_MD
	const _ = syscall.DNS_TYPE_MF
	const _ = syscall.DNS_TYPE_MG
	const _ = syscall.DNS_TYPE_MINFO
	const _ = syscall.DNS_TYPE_MR
	const _ = syscall.DNS_TYPE_MX
	const _ = syscall.DNS_TYPE_NAPTR
	const _ = syscall.DNS_TYPE_NBSTAT
	const _ = syscall.DNS_TYPE_NIMLOC
	const _ = syscall.DNS_TYPE_NS
	const _ = syscall.DNS_TYPE_NSAP
	const _ = syscall.DNS_TYPE_NSAPPTR
	const _ = syscall.DNS_TYPE_NSEC
	const _ = syscall.DNS_TYPE_NULL
}
