// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=f32ToI32 --function=f32ToU32 --function=f64ToUintptr --check-globals=none
package main

func f32ToI32(v float32) int32       { return int32(v) }
func f32ToU32(v float32) uint32      { return uint32(v) }
func f64ToUintptr(v float64) uintptr { return uintptr(v) }

// CHECK-LABEL: define i32 @main.f32ToI32(
// CHECK-SAME: float %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = fcmp ole float %[[TMP0]], 0xC1E0000000000000
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = fcmp oge float %[[TMP0]], 0x41E0000000000000
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = fcmp uno float %[[TMP0]], %[[TMP0]]
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], float 0.000000e+00, float %[[TMP0]]
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = select i1 %[[TMP2]], float 0.000000e+00, float %[[TMP4]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = select i1 %[[TMP3]], float 0.000000e+00, float %[[TMP5]]
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = fptosi float %[[TMP6]] to i32
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = select i1 %[[TMP1]], i32 -2147483648, i32 %[[TMP7]]
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = select i1 %[[TMP2]], i32 2147483647, i32 %[[TMP8]]
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = select i1 %[[TMP3]], i32 0, i32 %[[TMP9]]
// CHECK-NEXT:   ret i32 %[[TMP10]]
// CHECK-NEXT: }

// CHECK-LABEL: define i32 @main.f32ToU32(
// CHECK-SAME: float %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = fcmp ole float %[[TMP0]], 0xC3E0000000000000
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = fcmp oge float %[[TMP0]], 0x43E0000000000000
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = fcmp uno float %[[TMP0]], %[[TMP0]]
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], float 0.000000e+00, float %[[TMP0]]
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = select i1 %[[TMP2]], float 0.000000e+00, float %[[TMP4]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = select i1 %[[TMP3]], float 0.000000e+00, float %[[TMP5]]
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = fptosi float %[[TMP6]] to i64
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = select i1 %[[TMP1]], i64 -9223372036854775808, i64 %[[TMP7]]
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = select i1 %[[TMP2]], i64 9223372036854775807, i64 %[[TMP8]]
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = select i1 %[[TMP3]], i64 0, i64 %[[TMP9]]
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = trunc i64 %[[TMP10]] to i32
// CHECK-NEXT:   ret i32 %[[TMP11]]
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @main.f64ToUintptr(
// CHECK-SAME: double %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = fcmp olt double %[[TMP0]], 0.000000e+00
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = fcmp oge double %[[TMP0]], 0x43F0000000000000
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = fcmp uno double %[[TMP0]], %[[TMP0]]
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], double 0.000000e+00, double %[[TMP0]]
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = select i1 %[[TMP2]], double 0.000000e+00, double %[[TMP4]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = select i1 %[[TMP3]], double 0.000000e+00, double %[[TMP5]]
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = fptoui double %[[TMP6]] to i64
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = select i1 %[[TMP2]], i64 -1, i64 %[[TMP7]]
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = select i1 %[[TMP1]], i64 0, i64 %[[TMP8]]
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = select i1 %[[TMP3]], i64 0, i64 %[[TMP9]]
// CHECK-NEXT:   ret i64 %[[TMP10]]
// CHECK-NEXT: }
