// LITTEST darwin/arm64 linux/amd64
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.genInts\E|\Qmain.(*generator).next\E|\Qmain.main\E|\Qmain.main$1\E|\Qmain.(*generator).next$bound\E) --check-globals=smart
package main

import (
	"github.com/goplus/lib/c"
)

// genInts invokes the supplied code/environment pair once per output slot and
// stores that result into the slice at the checked loop index.

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1{{$}}

func genInts(n int, gen func() c.Int) []c.Int {
	a := make([]c.Int, n)
	for i := range a {
		a[i] = gen()
	}
	return a
}

func (g *generator) next() c.Int {
	g.val++
	return g.val
}

type generator struct {
	val c.Int
}

func main() {
	for _, v := range genInts(5, c.Rand) {

		c.Printf(c.Str("%d\n"), v)
	}

	initVal := c.Int(1)
	ints := genInts(5, func() c.Int {
		initVal *= 2
		return initVal
	})
	for _, v := range ints {
		c.Printf(c.Str("%d\n"), v)
	}

	g := &generator{val: 1}
	for _, v := range genInts(5, g.next) {
		c.Printf(c.Str("%d\n"), v)
	}
}

// CHECK-LABEL: define %"{{.*}}/runtime/internal/runtime.Slice" @main.genInts(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]], { ptr, ptr } %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.Slice" @"{{.*}}/runtime/internal/runtime.MakeSlice"(i64 %[[TMP0]], i64 %[[TMP0]], i64 4)
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP5:[0-9]+]], %_llgo_[[BB5:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP5]] = add i64 %[[TMP4]], 1
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = icmp slt i64 %[[TMP5]], %[[TMP3]]
// CHECK-NEXT:   br i1 %[[TMP6]], label %_llgo_[[BB2:[0-9]+]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP1]], 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP1]], 0
// CHECK-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP8]])
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = call i32 %__llgo_funcval_code(ptr swiftself %[[TMP7]])
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = call i32 %__llgo_funcval_code(ptr nest %[[TMP7]])
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 0
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = icmp slt i64 %[[TMP5]], 0
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = icmp uge i64 %[[TMP5]], %[[TMP11]]
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = or i1 %[[TMP13]], %[[TMP12]]
// CHECK-NEXT:   br i1 %[[TMP14]], label %_llgo_[[BB4:[0-9]+]], label %_llgo_[[BB5]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   ret %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicIndex"(i64 %[[TMP5]], i64 %[[TMP11]])
// CHECK-NEXT:   br label %_llgo_[[BB4]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP10]], i64 %[[TMP5]]
// CHECK-NEXT:   store i32 %[[TMP9]], ptr %[[TMP15]], align 4
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-NEXT: }

// CHECK-LABEL: define i32 @"main.(*generator).next"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load i32, ptr %[[TMP1]], align 4
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = add i32 %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   store i32 %[[TMP3]], ptr %[[TMP4]], align 4
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = load i32, ptr %[[TMP5]], align 4
// CHECK-NEXT:   ret i32 %[[TMP6]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.Slice" @main.genInts(i64 5, { ptr, ptr } { ptr @rand, ptr null })
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP3:[0-9]+]], %_llgo_[[BB11:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP3]] = add i64 %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = icmp slt i64 %[[TMP3]], %[[TMP1]]
// CHECK-NEXT:   br i1 %[[TMP4]], label %_llgo_[[BB2:[0-9]+]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = icmp slt i64 %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = icmp uge i64 %[[TMP3]], %[[TMP6]]
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = or i1 %[[TMP8]], %[[TMP7]]
// CHECK-NEXT:   br i1 %[[TMP9]], label %_llgo_[[BB10:[0-9]+]], label %_llgo_[[BB11]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 4)
// CHECK-NEXT:   store i32 1, ptr %[[TMP10]], align 4
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP11]], i32 0, i32 0
// CHECK-NEXT:   store ptr %[[TMP10]], ptr %[[TMP12]], align 8
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.main$1", ptr undef }, ptr %[[TMP11]], 1
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.Slice" @main.genInts(i64 5, { ptr, ptr } %[[TMP13]])
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP14]], 1
// CHECK-NEXT:   br label %_llgo_[[BB4:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB3]] ], [ %[[TMP17:[0-9]+]], %_llgo_[[BB13:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP17]] = add i64 %[[TMP16]], 1
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = icmp slt i64 %[[TMP17]], %[[TMP15]]
// CHECK-NEXT:   br i1 %[[TMP18]], label %_llgo_[[BB5:[0-9]+]], label %_llgo_[[BB6:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP14]], 0
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP14]], 1
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = icmp slt i64 %[[TMP17]], 0
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = icmp uge i64 %[[TMP17]], %[[TMP20]]
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = or i1 %[[TMP22]], %[[TMP21]]
// CHECK-NEXT:   br i1 %[[TMP23]], label %_llgo_[[BB12:[0-9]+]], label %_llgo_[[BB13]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB6]]:
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 4)
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP24]], i32 0, i32 0
// CHECK-NEXT:   store i32 1, ptr %[[TMP25]], align 4
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP26]], i32 0, i32 0
// CHECK-NEXT:   store ptr %[[TMP24]], ptr %[[TMP27]], align 8
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.(*generator).next$bound", ptr undef }, ptr %[[TMP26]], 1
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.Slice" @main.genInts(i64 5, { ptr, ptr } %[[TMP28]])
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP29]], 1
// CHECK-NEXT:   br label %_llgo_[[BB7:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB7]]:
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB6]] ], [ %[[TMP32:[0-9]+]], %_llgo_[[BB15:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP32]] = add i64 %[[TMP31]], 1
// CHECK-NEXT:   %[[TMP33:[0-9]+]] = icmp slt i64 %[[TMP32]], %[[TMP30]]
// CHECK-NEXT:   br i1 %[[TMP33]], label %_llgo_[[BB8:[0-9]+]], label %_llgo_[[BB9:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB8]]:
// CHECK-NEXT:   %[[TMP34:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP29]], 0
// CHECK-NEXT:   %[[TMP35:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP29]], 1
// CHECK-NEXT:   %[[TMP36:[0-9]+]] = icmp slt i64 %[[TMP32]], 0
// CHECK-NEXT:   %[[TMP37:[0-9]+]] = icmp uge i64 %[[TMP32]], %[[TMP35]]
// CHECK-NEXT:   %[[TMP38:[0-9]+]] = or i1 %[[TMP37]], %[[TMP36]]
// CHECK-NEXT:   br i1 %[[TMP38]], label %_llgo_[[BB14:[0-9]+]], label %_llgo_[[BB15]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB9]]:
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB10]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicIndex"(i64 %[[TMP3]], i64 %[[TMP6]])
// CHECK-NEXT:   br label %_llgo_[[BB10]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB11]]:
// CHECK-NEXT:   %[[TMP39:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP5]], i64 %[[TMP3]]
// CHECK-NEXT:   %[[TMP40:[0-9]+]] = load i32, ptr %[[TMP39]], align 4
// CHECK-NEXT:   %[[TMP41:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB0]], i32 %[[TMP40]])
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB12]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicIndex"(i64 %[[TMP17]], i64 %[[TMP20]])
// CHECK-NEXT:   br label %_llgo_[[BB12]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB13]]:
// CHECK-NEXT:   %[[TMP42:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP19]], i64 %[[TMP17]]
// CHECK-NEXT:   %[[TMP43:[0-9]+]] = load i32, ptr %[[TMP42]], align 4
// CHECK-NEXT:   %[[TMP44:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB1]], i32 %[[TMP43]])
// CHECK-NEXT:   br label %_llgo_[[BB4]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB14]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicIndex"(i64 %[[TMP32]], i64 %[[TMP35]])
// CHECK-NEXT:   br label %_llgo_[[BB14]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB15]]:
// CHECK-NEXT:   %[[TMP45:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP34]], i64 %[[TMP32]]
// CHECK-NEXT:   %[[TMP46:[0-9]+]] = load i32, ptr %[[TMP45]], align 4
// CHECK-NEXT:   %[[TMP47:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB2]], i32 %[[TMP46]])
// CHECK-NEXT:   br label %_llgo_[[BB7]]
// CHECK-NEXT: }

// CHECK-LABEL: define i32 @"main.main$1"(
// DARWIN-ARM64-SAME: ptr swiftself %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr nest %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = load { ptr }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load i32, ptr %[[TMP2]], align 4
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = mul i32 %[[TMP3]], 2
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   store i32 %[[TMP4]], ptr %[[TMP5]], align 4
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = load i32, ptr %[[TMP6]], align 4
// CHECK-NEXT:   ret i32 %[[TMP7]]
// CHECK-NEXT: }

// CHECK-LABEL: define i32 @"main.(*generator).next$bound"(
// DARWIN-ARM64-SAME: ptr swiftself %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr nest %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = load { ptr }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call i32 @"main.(*generator).next"(ptr %[[TMP2]])
// CHECK-NEXT:   ret i32 %[[TMP3]]
// CHECK-NEXT: }
