name: Targets

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  llgo:
    if: github.head_ref != 'codex/test-mingw-go-crash-2549-20260909'
    name: llgo (${{ matrix.test_dir }}, ${{ matrix.os }}, LLVM ${{ matrix.llvm }})
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        test_dir: [empty, defer]
        os:
          - ubuntu-latest
        llvm: [22]
    runs-on: ${{ github.repository_owner == 'xgo-dev' && fromJSON('["qiniu", "ubuntu-24.04-large"]') || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/setup-deps
        with:
          llvm-version: ${{matrix.llvm}}

      - name: Set up Go for build
        uses: ./.github/actions/setup-go

      - name: Install
        run: |
          go install ./...
          echo "LLGO_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Build targets (${{ matrix.test_dir }})
        working-directory: _demo/embed/targetsbuild
        run: bash build.sh "${{ matrix.test_dir }}"
